###################################################################

Name of the project: ivs project 2

###################################################################
#
# @file Makefile
# @brief This is a Makefile for second project of ivs
#
# @date 11.03.2023
#
# @author Matúš Hubinský
# @author Adam Ďurica
# @author Boris Hatala
#
# ##################################################################


















### End of file Makefile ###
